#include "curlopts.h"
#include <absl/strings/str_cat.h>

std::string_view CurlOptToString(CURLoption opt) {
  static std::string unknown;
#define CURLOPT2(na, t, nu) \
  case ((t) + (nu)):        \
    return #na;
  switch (opt) {
    CURLOPT2(CURLOPT_WRITEDATA, CURLOPTTYPE_CBPOINT, 1);
    CURLOPT2(CURLOPT_URL, CURLOPTTYPE_STRINGPOINT, 2);
    CURLOPT2(CURLOPT_PORT, CURLOPTTYPE_LONG, 3);
    CURLOPT2(CURLOPT_PROXY, CURLOPTTYPE_STRINGPOINT, 4);
    CURLOPT2(CURLOPT_USERPWD, CURLOPTTYPE_STRINGPOINT, 5);
    CURLOPT2(CURLOPT_PROXYUSERPWD, CURLOPTTYPE_STRINGPOINT, 6);
    CURLOPT2(CURLOPT_RANGE, CURLOPTTYPE_STRINGPOINT, 7);
    CURLOPT2(CURLOPT_READDATA, CURLOPTTYPE_CBPOINT, 9);
    CURLOPT2(CURLOPT_ERRORBUFFER, CURLOPTTYPE_OBJECTPOINT, 10);
    CURLOPT2(CURLOPT_WRITEFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 11);
    CURLOPT2(CURLOPT_READFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 12);
    CURLOPT2(CURLOPT_TIMEOUT, CURLOPTTYPE_LONG, 13);
    CURLOPT2(CURLOPT_INFILESIZE, CURLOPTTYPE_LONG, 14);
    CURLOPT2(CURLOPT_POSTFIELDS, CURLOPTTYPE_OBJECTPOINT, 15);
    CURLOPT2(CURLOPT_REFERER, CURLOPTTYPE_STRINGPOINT, 16);
    CURLOPT2(CURLOPT_FTPPORT, CURLOPTTYPE_STRINGPOINT, 17);
    CURLOPT2(CURLOPT_USERAGENT, CURLOPTTYPE_STRINGPOINT, 18);
    CURLOPT2(CURLOPT_LOW_SPEED_LIMIT, CURLOPTTYPE_LONG, 19);
    CURLOPT2(CURLOPT_LOW_SPEED_TIME, CURLOPTTYPE_LONG, 20);
    CURLOPT2(CURLOPT_RESUME_FROM, CURLOPTTYPE_LONG, 21);
    CURLOPT2(CURLOPT_COOKIE, CURLOPTTYPE_STRINGPOINT, 22);
    CURLOPT2(CURLOPT_HTTPHEADER, CURLOPTTYPE_SLISTPOINT, 23);
    CURLOPT2(CURLOPT_SSLCERT, CURLOPTTYPE_STRINGPOINT, 25);
    CURLOPT2(CURLOPT_KEYPASSWD, CURLOPTTYPE_STRINGPOINT, 26);
    CURLOPT2(CURLOPT_CRLF, CURLOPTTYPE_LONG, 27);
    CURLOPT2(CURLOPT_QUOTE, CURLOPTTYPE_SLISTPOINT, 28);
    CURLOPT2(CURLOPT_HEADERDATA, CURLOPTTYPE_CBPOINT, 29);
    CURLOPT2(CURLOPT_COOKIEFILE, CURLOPTTYPE_STRINGPOINT, 31);
    CURLOPT2(CURLOPT_SSLVERSION, CURLOPTTYPE_VALUES, 32);
    CURLOPT2(CURLOPT_TIMECONDITION, CURLOPTTYPE_VALUES, 33);
    CURLOPT2(CURLOPT_TIMEVALUE, CURLOPTTYPE_LONG, 34);
    CURLOPT2(CURLOPT_CUSTOMREQUEST, CURLOPTTYPE_STRINGPOINT, 36);
    CURLOPT2(CURLOPT_STDERR, CURLOPTTYPE_OBJECTPOINT, 37);
    CURLOPT2(CURLOPT_POSTQUOTE, CURLOPTTYPE_SLISTPOINT, 39);
    CURLOPT2(CURLOPT_VERBOSE, CURLOPTTYPE_LONG, 41);
    CURLOPT2(CURLOPT_HEADER, CURLOPTTYPE_LONG, 42);
    CURLOPT2(CURLOPT_NOPROGRESS, CURLOPTTYPE_LONG, 43);
    CURLOPT2(CURLOPT_NOBODY, CURLOPTTYPE_LONG, 44);
    CURLOPT2(CURLOPT_FAILONERROR, CURLOPTTYPE_LONG, 45);
    CURLOPT2(CURLOPT_UPLOAD, CURLOPTTYPE_LONG, 46);
    CURLOPT2(CURLOPT_POST, CURLOPTTYPE_LONG, 47);
    CURLOPT2(CURLOPT_DIRLISTONLY, CURLOPTTYPE_LONG, 48);
    CURLOPT2(CURLOPT_APPEND, CURLOPTTYPE_LONG, 50);
    CURLOPT2(CURLOPT_NETRC, CURLOPTTYPE_VALUES, 51);
    CURLOPT2(CURLOPT_FOLLOWLOCATION, CURLOPTTYPE_LONG, 52);
    CURLOPT2(CURLOPT_TRANSFERTEXT, CURLOPTTYPE_LONG, 53);
    CURLOPT2(CURLOPT_XFERINFODATA, CURLOPTTYPE_CBPOINT, 57);
    CURLOPT2(CURLOPT_AUTOREFERER, CURLOPTTYPE_LONG, 58);
    CURLOPT2(CURLOPT_PROXYPORT, CURLOPTTYPE_LONG, 59);
    CURLOPT2(CURLOPT_POSTFIELDSIZE, CURLOPTTYPE_LONG, 60);
    CURLOPT2(CURLOPT_HTTPPROXYTUNNEL, CURLOPTTYPE_LONG, 61);
    CURLOPT2(CURLOPT_INTERFACE, CURLOPTTYPE_STRINGPOINT, 62);
    CURLOPT2(CURLOPT_SSL_VERIFYPEER, CURLOPTTYPE_LONG, 64);
    CURLOPT2(CURLOPT_CAINFO, CURLOPTTYPE_STRINGPOINT, 65);
    CURLOPT2(CURLOPT_MAXREDIRS, CURLOPTTYPE_LONG, 68);
    CURLOPT2(CURLOPT_FILETIME, CURLOPTTYPE_LONG, 69);
    CURLOPT2(CURLOPT_TELNETOPTIONS, CURLOPTTYPE_SLISTPOINT, 70);
    CURLOPT2(CURLOPT_MAXCONNECTS, CURLOPTTYPE_LONG, 71);
    CURLOPT2(CURLOPT_FRESH_CONNECT, CURLOPTTYPE_LONG, 74);
    CURLOPT2(CURLOPT_FORBID_REUSE, CURLOPTTYPE_LONG, 75);
    CURLOPT2(CURLOPT_CONNECTTIMEOUT, CURLOPTTYPE_LONG, 78);
    CURLOPT2(CURLOPT_HEADERFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 79);
    CURLOPT2(CURLOPT_HTTPGET, CURLOPTTYPE_LONG, 80);
    CURLOPT2(CURLOPT_SSL_VERIFYHOST, CURLOPTTYPE_LONG, 81);
    CURLOPT2(CURLOPT_COOKIEJAR, CURLOPTTYPE_STRINGPOINT, 82);
    CURLOPT2(CURLOPT_SSL_CIPHER_LIST, CURLOPTTYPE_STRINGPOINT, 83);
    CURLOPT2(CURLOPT_HTTP_VERSION, CURLOPTTYPE_VALUES, 84);
    CURLOPT2(CURLOPT_FTP_USE_EPSV, CURLOPTTYPE_LONG, 85);
    CURLOPT2(CURLOPT_SSLCERTTYPE, CURLOPTTYPE_STRINGPOINT, 86);
    CURLOPT2(CURLOPT_SSLKEY, CURLOPTTYPE_STRINGPOINT, 87);
    CURLOPT2(CURLOPT_SSLKEYTYPE, CURLOPTTYPE_STRINGPOINT, 88);
    CURLOPT2(CURLOPT_SSLENGINE, CURLOPTTYPE_STRINGPOINT, 89);
    CURLOPT2(CURLOPT_SSLENGINE_DEFAULT, CURLOPTTYPE_LONG, 90);
    CURLOPT2(CURLOPT_DNS_CACHE_TIMEOUT, CURLOPTTYPE_LONG, 92);
    CURLOPT2(CURLOPT_PREQUOTE, CURLOPTTYPE_SLISTPOINT, 93);
    CURLOPT2(CURLOPT_DEBUGFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 94);
    CURLOPT2(CURLOPT_DEBUGDATA, CURLOPTTYPE_CBPOINT, 95);
    CURLOPT2(CURLOPT_COOKIESESSION, CURLOPTTYPE_LONG, 96);
    CURLOPT2(CURLOPT_CAPATH, CURLOPTTYPE_STRINGPOINT, 97);
    CURLOPT2(CURLOPT_BUFFERSIZE, CURLOPTTYPE_LONG, 98);
    CURLOPT2(CURLOPT_NOSIGNAL, CURLOPTTYPE_LONG, 99);
    CURLOPT2(CURLOPT_SHARE, CURLOPTTYPE_OBJECTPOINT, 100);
    CURLOPT2(CURLOPT_PROXYTYPE, CURLOPTTYPE_VALUES, 101);
    CURLOPT2(CURLOPT_ACCEPT_ENCODING, CURLOPTTYPE_STRINGPOINT, 102);
    CURLOPT2(CURLOPT_PRIVATE, CURLOPTTYPE_OBJECTPOINT, 103);
    CURLOPT2(CURLOPT_HTTP200ALIASES, CURLOPTTYPE_SLISTPOINT, 104);
    CURLOPT2(CURLOPT_UNRESTRICTED_AUTH, CURLOPTTYPE_LONG, 105);
    CURLOPT2(CURLOPT_FTP_USE_EPRT, CURLOPTTYPE_LONG, 106);
    CURLOPT2(CURLOPT_HTTPAUTH, CURLOPTTYPE_VALUES, 107);
    CURLOPT2(CURLOPT_SSL_CTX_FUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 108);
    CURLOPT2(CURLOPT_SSL_CTX_DATA, CURLOPTTYPE_CBPOINT, 109);
    CURLOPT2(CURLOPT_FTP_CREATE_MISSING_DIRS, CURLOPTTYPE_LONG, 110);
    CURLOPT2(CURLOPT_PROXYAUTH, CURLOPTTYPE_VALUES, 111);
    CURLOPT2(CURLOPT_SERVER_RESPONSE_TIMEOUT, CURLOPTTYPE_LONG, 112);
    CURLOPT2(CURLOPT_IPRESOLVE, CURLOPTTYPE_VALUES, 113);
    CURLOPT2(CURLOPT_MAXFILESIZE, CURLOPTTYPE_LONG, 114);
    CURLOPT2(CURLOPT_INFILESIZE_LARGE, CURLOPTTYPE_OFF_T, 115);
    CURLOPT2(CURLOPT_RESUME_FROM_LARGE, CURLOPTTYPE_OFF_T, 116);
    CURLOPT2(CURLOPT_MAXFILESIZE_LARGE, CURLOPTTYPE_OFF_T, 117);
    CURLOPT2(CURLOPT_NETRC_FILE, CURLOPTTYPE_STRINGPOINT, 118);
    CURLOPT2(CURLOPT_USE_SSL, CURLOPTTYPE_VALUES, 119);
    CURLOPT2(CURLOPT_POSTFIELDSIZE_LARGE, CURLOPTTYPE_OFF_T, 120);
    CURLOPT2(CURLOPT_TCP_NODELAY, CURLOPTTYPE_LONG, 121);
    CURLOPT2(CURLOPT_FTPSSLAUTH, CURLOPTTYPE_VALUES, 129);
    CURLOPT2(CURLOPT_FTP_ACCOUNT, CURLOPTTYPE_STRINGPOINT, 134);
    CURLOPT2(CURLOPT_COOKIELIST, CURLOPTTYPE_STRINGPOINT, 135);
    CURLOPT2(CURLOPT_IGNORE_CONTENT_LENGTH, CURLOPTTYPE_LONG, 136);
    CURLOPT2(CURLOPT_FTP_SKIP_PASV_IP, CURLOPTTYPE_LONG, 137);
    CURLOPT2(CURLOPT_FTP_FILEMETHOD, CURLOPTTYPE_VALUES, 138);
    CURLOPT2(CURLOPT_LOCALPORT, CURLOPTTYPE_LONG, 139);
    CURLOPT2(CURLOPT_LOCALPORTRANGE, CURLOPTTYPE_LONG, 140);
    CURLOPT2(CURLOPT_CONNECT_ONLY, CURLOPTTYPE_LONG, 141);
    CURLOPT2(CURLOPT_MAX_SEND_SPEED_LARGE, CURLOPTTYPE_OFF_T, 145);
    CURLOPT2(CURLOPT_MAX_RECV_SPEED_LARGE, CURLOPTTYPE_OFF_T, 146);
    CURLOPT2(CURLOPT_FTP_ALTERNATIVE_TO_USER, CURLOPTTYPE_STRINGPOINT, 147);
    CURLOPT2(CURLOPT_SOCKOPTFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 148);
    CURLOPT2(CURLOPT_SOCKOPTDATA, CURLOPTTYPE_CBPOINT, 149);
    CURLOPT2(CURLOPT_SSL_SESSIONID_CACHE, CURLOPTTYPE_LONG, 150);
    CURLOPT2(CURLOPT_SSH_AUTH_TYPES, CURLOPTTYPE_VALUES, 151);
    CURLOPT2(CURLOPT_SSH_PUBLIC_KEYFILE, CURLOPTTYPE_STRINGPOINT, 152);
    CURLOPT2(CURLOPT_SSH_PRIVATE_KEYFILE, CURLOPTTYPE_STRINGPOINT, 153);
    CURLOPT2(CURLOPT_FTP_SSL_CCC, CURLOPTTYPE_LONG, 154);
    CURLOPT2(CURLOPT_TIMEOUT_MS, CURLOPTTYPE_LONG, 155);
    CURLOPT2(CURLOPT_CONNECTTIMEOUT_MS, CURLOPTTYPE_LONG, 156);
    CURLOPT2(CURLOPT_HTTP_TRANSFER_DECODING, CURLOPTTYPE_LONG, 157);
    CURLOPT2(CURLOPT_HTTP_CONTENT_DECODING, CURLOPTTYPE_LONG, 158);
    CURLOPT2(CURLOPT_NEW_FILE_PERMS, CURLOPTTYPE_LONG, 159);
    CURLOPT2(CURLOPT_NEW_DIRECTORY_PERMS, CURLOPTTYPE_LONG, 160);
    CURLOPT2(CURLOPT_POSTREDIR, CURLOPTTYPE_VALUES, 161);
    CURLOPT2(CURLOPT_SSH_HOST_PUBLIC_KEY_MD5, CURLOPTTYPE_STRINGPOINT, 162);
    CURLOPT2(CURLOPT_OPENSOCKETFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 163);
    CURLOPT2(CURLOPT_OPENSOCKETDATA, CURLOPTTYPE_CBPOINT, 164);
    CURLOPT2(CURLOPT_COPYPOSTFIELDS, CURLOPTTYPE_OBJECTPOINT, 165);
    CURLOPT2(CURLOPT_PROXY_TRANSFER_MODE, CURLOPTTYPE_LONG, 166);
    CURLOPT2(CURLOPT_SEEKFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 167);
    CURLOPT2(CURLOPT_SEEKDATA, CURLOPTTYPE_CBPOINT, 168);
    CURLOPT2(CURLOPT_CRLFILE, CURLOPTTYPE_STRINGPOINT, 169);
    CURLOPT2(CURLOPT_ISSUERCERT, CURLOPTTYPE_STRINGPOINT, 170);
    CURLOPT2(CURLOPT_ADDRESS_SCOPE, CURLOPTTYPE_LONG, 171);
    CURLOPT2(CURLOPT_CERTINFO, CURLOPTTYPE_LONG, 172);
    CURLOPT2(CURLOPT_USERNAME, CURLOPTTYPE_STRINGPOINT, 173);
    CURLOPT2(CURLOPT_PASSWORD, CURLOPTTYPE_STRINGPOINT, 174);
    CURLOPT2(CURLOPT_PROXYUSERNAME, CURLOPTTYPE_STRINGPOINT, 175);
    CURLOPT2(CURLOPT_PROXYPASSWORD, CURLOPTTYPE_STRINGPOINT, 176);
    CURLOPT2(CURLOPT_NOPROXY, CURLOPTTYPE_STRINGPOINT, 177);
    CURLOPT2(CURLOPT_TFTP_BLKSIZE, CURLOPTTYPE_LONG, 178);
    CURLOPT2(CURLOPT_SOCKS5_GSSAPI_NEC, CURLOPTTYPE_LONG, 180);
    CURLOPT2(CURLOPT_SSH_KNOWNHOSTS, CURLOPTTYPE_STRINGPOINT, 183);
    CURLOPT2(CURLOPT_SSH_KEYFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 184);
    CURLOPT2(CURLOPT_SSH_KEYDATA, CURLOPTTYPE_CBPOINT, 185);
    CURLOPT2(CURLOPT_MAIL_FROM, CURLOPTTYPE_STRINGPOINT, 186);
    CURLOPT2(CURLOPT_MAIL_RCPT, CURLOPTTYPE_SLISTPOINT, 187);
    CURLOPT2(CURLOPT_FTP_USE_PRET, CURLOPTTYPE_LONG, 188);
    CURLOPT2(CURLOPT_RTSP_REQUEST, CURLOPTTYPE_VALUES, 189);
    CURLOPT2(CURLOPT_RTSP_SESSION_ID, CURLOPTTYPE_STRINGPOINT, 190);
    CURLOPT2(CURLOPT_RTSP_STREAM_URI, CURLOPTTYPE_STRINGPOINT, 191);
    CURLOPT2(CURLOPT_RTSP_TRANSPORT, CURLOPTTYPE_STRINGPOINT, 192);
    CURLOPT2(CURLOPT_RTSP_CLIENT_CSEQ, CURLOPTTYPE_LONG, 193);
    CURLOPT2(CURLOPT_RTSP_SERVER_CSEQ, CURLOPTTYPE_LONG, 194);
    CURLOPT2(CURLOPT_INTERLEAVEDATA, CURLOPTTYPE_CBPOINT, 195);
    CURLOPT2(CURLOPT_INTERLEAVEFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 196);
    CURLOPT2(CURLOPT_WILDCARDMATCH, CURLOPTTYPE_LONG, 197);
    CURLOPT2(CURLOPT_CHUNK_BGN_FUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 198);
    CURLOPT2(CURLOPT_CHUNK_END_FUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 199);
    CURLOPT2(CURLOPT_FNMATCH_FUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 200);
    CURLOPT2(CURLOPT_CHUNK_DATA, CURLOPTTYPE_CBPOINT, 201);
    CURLOPT2(CURLOPT_FNMATCH_DATA, CURLOPTTYPE_CBPOINT, 202);
    CURLOPT2(CURLOPT_RESOLVE, CURLOPTTYPE_SLISTPOINT, 203);
    CURLOPT2(CURLOPT_TLSAUTH_USERNAME, CURLOPTTYPE_STRINGPOINT, 204);
    CURLOPT2(CURLOPT_TLSAUTH_PASSWORD, CURLOPTTYPE_STRINGPOINT, 205);
    CURLOPT2(CURLOPT_TLSAUTH_TYPE, CURLOPTTYPE_STRINGPOINT, 206);
    CURLOPT2(CURLOPT_TRANSFER_ENCODING, CURLOPTTYPE_LONG, 207);
    CURLOPT2(CURLOPT_CLOSESOCKETFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 208);
    CURLOPT2(CURLOPT_CLOSESOCKETDATA, CURLOPTTYPE_CBPOINT, 209);
    CURLOPT2(CURLOPT_GSSAPI_DELEGATION, CURLOPTTYPE_VALUES, 210);
    CURLOPT2(CURLOPT_DNS_SERVERS, CURLOPTTYPE_STRINGPOINT, 211);
    CURLOPT2(CURLOPT_ACCEPTTIMEOUT_MS, CURLOPTTYPE_LONG, 212);
    CURLOPT2(CURLOPT_TCP_KEEPALIVE, CURLOPTTYPE_LONG, 213);
    CURLOPT2(CURLOPT_TCP_KEEPIDLE, CURLOPTTYPE_LONG, 214);
    CURLOPT2(CURLOPT_TCP_KEEPINTVL, CURLOPTTYPE_LONG, 215);
    CURLOPT2(CURLOPT_SSL_OPTIONS, CURLOPTTYPE_VALUES, 216);
    CURLOPT2(CURLOPT_MAIL_AUTH, CURLOPTTYPE_STRINGPOINT, 217);
    CURLOPT2(CURLOPT_SASL_IR, CURLOPTTYPE_LONG, 218);
    CURLOPT2(CURLOPT_XFERINFOFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 219);
    CURLOPT2(CURLOPT_XOAUTH2_BEARER, CURLOPTTYPE_STRINGPOINT, 220);
    CURLOPT2(CURLOPT_DNS_INTERFACE, CURLOPTTYPE_STRINGPOINT, 221);
    CURLOPT2(CURLOPT_DNS_LOCAL_IP4, CURLOPTTYPE_STRINGPOINT, 222);
    CURLOPT2(CURLOPT_DNS_LOCAL_IP6, CURLOPTTYPE_STRINGPOINT, 223);
    CURLOPT2(CURLOPT_LOGIN_OPTIONS, CURLOPTTYPE_STRINGPOINT, 224);
    CURLOPT2(CURLOPT_SSL_ENABLE_ALPN, CURLOPTTYPE_LONG, 226);
    CURLOPT2(CURLOPT_EXPECT_100_TIMEOUT_MS, CURLOPTTYPE_LONG, 227);
    CURLOPT2(CURLOPT_PROXYHEADER, CURLOPTTYPE_SLISTPOINT, 228);
    CURLOPT2(CURLOPT_HEADEROPT, CURLOPTTYPE_VALUES, 229);
    CURLOPT2(CURLOPT_PINNEDPUBLICKEY, CURLOPTTYPE_STRINGPOINT, 230);
    CURLOPT2(CURLOPT_UNIX_SOCKET_PATH, CURLOPTTYPE_STRINGPOINT, 231);
    CURLOPT2(CURLOPT_SSL_VERIFYSTATUS, CURLOPTTYPE_LONG, 232);
    CURLOPT2(CURLOPT_PATH_AS_IS, CURLOPTTYPE_LONG, 234);
    CURLOPT2(CURLOPT_PROXY_SERVICE_NAME, CURLOPTTYPE_STRINGPOINT, 235);
    CURLOPT2(CURLOPT_SERVICE_NAME, CURLOPTTYPE_STRINGPOINT, 236);
    CURLOPT2(CURLOPT_PIPEWAIT, CURLOPTTYPE_LONG, 237);
    CURLOPT2(CURLOPT_DEFAULT_PROTOCOL, CURLOPTTYPE_STRINGPOINT, 238);
    CURLOPT2(CURLOPT_STREAM_WEIGHT, CURLOPTTYPE_LONG, 239);
    CURLOPT2(CURLOPT_TFTP_NO_OPTIONS, CURLOPTTYPE_LONG, 242);
    CURLOPT2(CURLOPT_CONNECT_TO, CURLOPTTYPE_SLISTPOINT, 243);
    CURLOPT2(CURLOPT_TCP_FASTOPEN, CURLOPTTYPE_LONG, 244);
    CURLOPT2(CURLOPT_KEEP_SENDING_ON_ERROR, CURLOPTTYPE_LONG, 245);
    CURLOPT2(CURLOPT_PROXY_CAINFO, CURLOPTTYPE_STRINGPOINT, 246);
    CURLOPT2(CURLOPT_PROXY_CAPATH, CURLOPTTYPE_STRINGPOINT, 247);
    CURLOPT2(CURLOPT_PROXY_SSL_VERIFYPEER, CURLOPTTYPE_LONG, 248);
    CURLOPT2(CURLOPT_PROXY_SSL_VERIFYHOST, CURLOPTTYPE_LONG, 249);
    CURLOPT2(CURLOPT_PROXY_SSLVERSION, CURLOPTTYPE_VALUES, 250);
    CURLOPT2(CURLOPT_PROXY_TLSAUTH_USERNAME, CURLOPTTYPE_STRINGPOINT, 251);
    CURLOPT2(CURLOPT_PROXY_TLSAUTH_PASSWORD, CURLOPTTYPE_STRINGPOINT, 252);
    CURLOPT2(CURLOPT_PROXY_TLSAUTH_TYPE, CURLOPTTYPE_STRINGPOINT, 253);
    CURLOPT2(CURLOPT_PROXY_SSLCERT, CURLOPTTYPE_STRINGPOINT, 254);
    CURLOPT2(CURLOPT_PROXY_SSLCERTTYPE, CURLOPTTYPE_STRINGPOINT, 255);
    CURLOPT2(CURLOPT_PROXY_SSLKEY, CURLOPTTYPE_STRINGPOINT, 256);
    CURLOPT2(CURLOPT_PROXY_SSLKEYTYPE, CURLOPTTYPE_STRINGPOINT, 257);
    CURLOPT2(CURLOPT_PROXY_KEYPASSWD, CURLOPTTYPE_STRINGPOINT, 258);
    CURLOPT2(CURLOPT_PROXY_SSL_CIPHER_LIST, CURLOPTTYPE_STRINGPOINT, 259);
    CURLOPT2(CURLOPT_PROXY_CRLFILE, CURLOPTTYPE_STRINGPOINT, 260);
    CURLOPT2(CURLOPT_PROXY_SSL_OPTIONS, CURLOPTTYPE_LONG, 261);
    CURLOPT2(CURLOPT_PRE_PROXY, CURLOPTTYPE_STRINGPOINT, 262);
    CURLOPT2(CURLOPT_PROXY_PINNEDPUBLICKEY, CURLOPTTYPE_STRINGPOINT, 263);
    CURLOPT2(CURLOPT_ABSTRACT_UNIX_SOCKET, CURLOPTTYPE_STRINGPOINT, 264);
    CURLOPT2(CURLOPT_SUPPRESS_CONNECT_HEADERS, CURLOPTTYPE_LONG, 265);
    CURLOPT2(CURLOPT_REQUEST_TARGET, CURLOPTTYPE_STRINGPOINT, 266);
    CURLOPT2(CURLOPT_SOCKS5_AUTH, CURLOPTTYPE_LONG, 267);
    CURLOPT2(CURLOPT_SSH_COMPRESSION, CURLOPTTYPE_LONG, 268);
    CURLOPT2(CURLOPT_MIMEPOST, CURLOPTTYPE_OBJECTPOINT, 269);
    CURLOPT2(CURLOPT_TIMEVALUE_LARGE, CURLOPTTYPE_OFF_T, 270);
    CURLOPT2(CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS, CURLOPTTYPE_LONG, 271);
    CURLOPT2(CURLOPT_RESOLVER_START_FUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 272);
    CURLOPT2(CURLOPT_RESOLVER_START_DATA, CURLOPTTYPE_CBPOINT, 273);
    CURLOPT2(CURLOPT_HAPROXYPROTOCOL, CURLOPTTYPE_LONG, 274);
    CURLOPT2(CURLOPT_DNS_SHUFFLE_ADDRESSES, CURLOPTTYPE_LONG, 275);
    CURLOPT2(CURLOPT_TLS13_CIPHERS, CURLOPTTYPE_STRINGPOINT, 276);
    CURLOPT2(CURLOPT_PROXY_TLS13_CIPHERS, CURLOPTTYPE_STRINGPOINT, 277);
    CURLOPT2(CURLOPT_DISALLOW_USERNAME_IN_URL, CURLOPTTYPE_LONG, 278);
    CURLOPT2(CURLOPT_DOH_URL, CURLOPTTYPE_STRINGPOINT, 279);
    CURLOPT2(CURLOPT_UPLOAD_BUFFERSIZE, CURLOPTTYPE_LONG, 280);
    CURLOPT2(CURLOPT_UPKEEP_INTERVAL_MS, CURLOPTTYPE_LONG, 281);
    CURLOPT2(CURLOPT_CURLU, CURLOPTTYPE_OBJECTPOINT, 282);
    CURLOPT2(CURLOPT_TRAILERFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 283);
    CURLOPT2(CURLOPT_TRAILERDATA, CURLOPTTYPE_CBPOINT, 284);
    CURLOPT2(CURLOPT_HTTP09_ALLOWED, CURLOPTTYPE_LONG, 285);
    CURLOPT2(CURLOPT_ALTSVC_CTRL, CURLOPTTYPE_LONG, 286);
    CURLOPT2(CURLOPT_ALTSVC, CURLOPTTYPE_STRINGPOINT, 287);
    CURLOPT2(CURLOPT_MAXAGE_CONN, CURLOPTTYPE_LONG, 288);
    CURLOPT2(CURLOPT_SASL_AUTHZID, CURLOPTTYPE_STRINGPOINT, 289);
    CURLOPT2(CURLOPT_MAIL_RCPT_ALLOWFAILS, CURLOPTTYPE_LONG, 290);
    CURLOPT2(CURLOPT_SSLCERT_BLOB, CURLOPTTYPE_BLOB, 291);
    CURLOPT2(CURLOPT_SSLKEY_BLOB, CURLOPTTYPE_BLOB, 292);
    CURLOPT2(CURLOPT_PROXY_SSLCERT_BLOB, CURLOPTTYPE_BLOB, 293);
    CURLOPT2(CURLOPT_PROXY_SSLKEY_BLOB, CURLOPTTYPE_BLOB, 294);
    CURLOPT2(CURLOPT_ISSUERCERT_BLOB, CURLOPTTYPE_BLOB, 295);
    CURLOPT2(CURLOPT_PROXY_ISSUERCERT, CURLOPTTYPE_STRINGPOINT, 296);
    CURLOPT2(CURLOPT_PROXY_ISSUERCERT_BLOB, CURLOPTTYPE_BLOB, 297);
    CURLOPT2(CURLOPT_SSL_EC_CURVES, CURLOPTTYPE_STRINGPOINT, 298);
    CURLOPT2(CURLOPT_HSTS_CTRL, CURLOPTTYPE_LONG, 299);
    CURLOPT2(CURLOPT_HSTS, CURLOPTTYPE_STRINGPOINT, 300);
    CURLOPT2(CURLOPT_HSTSREADFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 301);
    CURLOPT2(CURLOPT_HSTSREADDATA, CURLOPTTYPE_CBPOINT, 302);
    CURLOPT2(CURLOPT_HSTSWRITEFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 303);
    CURLOPT2(CURLOPT_HSTSWRITEDATA, CURLOPTTYPE_CBPOINT, 304);
    CURLOPT2(CURLOPT_AWS_SIGV4, CURLOPTTYPE_STRINGPOINT, 305);
    CURLOPT2(CURLOPT_DOH_SSL_VERIFYPEER, CURLOPTTYPE_LONG, 306);
    CURLOPT2(CURLOPT_DOH_SSL_VERIFYHOST, CURLOPTTYPE_LONG, 307);
    CURLOPT2(CURLOPT_DOH_SSL_VERIFYSTATUS, CURLOPTTYPE_LONG, 308);
    CURLOPT2(CURLOPT_CAINFO_BLOB, CURLOPTTYPE_BLOB, 309);
    CURLOPT2(CURLOPT_PROXY_CAINFO_BLOB, CURLOPTTYPE_BLOB, 310);
    CURLOPT2(CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256, CURLOPTTYPE_STRINGPOINT, 311);
    CURLOPT2(CURLOPT_PREREQFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 312);
    CURLOPT2(CURLOPT_PREREQDATA, CURLOPTTYPE_CBPOINT, 313);
    CURLOPT2(CURLOPT_MAXLIFETIME_CONN, CURLOPTTYPE_LONG, 314);
    CURLOPT2(CURLOPT_MIME_OPTIONS, CURLOPTTYPE_LONG, 315);
    CURLOPT2(CURLOPT_SSH_HOSTKEYFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 316);
    CURLOPT2(CURLOPT_SSH_HOSTKEYDATA, CURLOPTTYPE_CBPOINT, 317);
    CURLOPT2(CURLOPT_PROTOCOLS_STR, CURLOPTTYPE_STRINGPOINT, 318);
    CURLOPT2(CURLOPT_REDIR_PROTOCOLS_STR, CURLOPTTYPE_STRINGPOINT, 319);
    CURLOPT2(CURLOPT_WS_OPTIONS, CURLOPTTYPE_LONG, 320);
    CURLOPT2(CURLOPT_CA_CACHE_TIMEOUT, CURLOPTTYPE_LONG, 321);
    CURLOPT2(CURLOPT_QUICK_EXIT, CURLOPTTYPE_LONG, 322);
    CURLOPT2(CURLOPT_HAPROXY_CLIENT_IP, CURLOPTTYPE_STRINGPOINT, 323);
    CURLOPT2(CURLOPT_SERVER_RESPONSE_TIMEOUT_MS, CURLOPTTYPE_LONG, 324);
    CURLOPT2(CURLOPT_ECH, CURLOPTTYPE_STRINGPOINT, 325);
    CURLOPT2(CURLOPT_TCP_KEEPCNT, CURLOPTTYPE_LONG, 326);
    CURLOPT2(CURLOPT_UPLOAD_FLAGS, CURLOPTTYPE_LONG, 327);
    CURLOPT2(CURLOPT_SSL_SIGNATURE_ALGORITHMS, CURLOPTTYPE_STRINGPOINT, 328);
    default:
      unknown = absl::StrCat("<unknown CURLOPT: ", std::to_underlying(opt), ">");
      return unknown;
  }
#undef CURLOPT2
}
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
std::string_view CurlInfoToString(CURLINFO info) {
  static std::string unknown;
  switch (info) {
    case CURLINFO_NONE:
      return "CURLINFO_NONE"sv;
    case CURLINFO_EFFECTIVE_URL:
      return "CURLINFO_EFFECTIVE_URL"sv;
    case CURLINFO_RESPONSE_CODE:
      return "CURLINFO_RESPONSE_CODE"sv;
    case CURLINFO_TOTAL_TIME:
      return "CURLINFO_TOTAL_TIME"sv;
    case CURLINFO_NAMELOOKUP_TIME:
      return "CURLINFO_NAMELOOKUP_TIME"sv;
    case CURLINFO_CONNECT_TIME:
      return "CURLINFO_CONNECT_TIME"sv;
    case CURLINFO_PRETRANSFER_TIME:
      return "CURLINFO_PRETRANSFER_TIME"sv;
    case CURLINFO_SIZE_UPLOAD:
      return "CURLINFO_SIZE_UPLOAD"sv;
    case CURLINFO_SIZE_UPLOAD_T:
      return "CURLINFO_SIZE_UPLOAD_T"sv;
    case CURLINFO_SIZE_DOWNLOAD:
      return "CURLINFO_SIZE_DOWNLOAD"sv;
    case CURLINFO_SIZE_DOWNLOAD_T:
      return "CURLINFO_SIZE_DOWNLOAD_T"sv;
    case CURLINFO_SPEED_DOWNLOAD:
      return "CURLINFO_SPEED_DOWNLOAD"sv;
    case CURLINFO_SPEED_DOWNLOAD_T:
      return "CURLINFO_SPEED_DOWNLOAD_T"sv;
    case CURLINFO_SPEED_UPLOAD:
      return "CURLINFO_SPEED_UPLOAD"sv;
    case CURLINFO_SPEED_UPLOAD_T:
      return "CURLINFO_SPEED_UPLOAD_T"sv;
    case CURLINFO_HEADER_SIZE:
      return "CURLINFO_HEADER_SIZE"sv;
    case CURLINFO_REQUEST_SIZE:
      return "CURLINFO_REQUEST_SIZE"sv;
    case CURLINFO_SSL_VERIFYRESULT:
      return "CURLINFO_SSL_VERIFYRESULT"sv;
    case CURLINFO_FILETIME:
      return "CURLINFO_FILETIME"sv;
    case CURLINFO_FILETIME_T:
      return "CURLINFO_FILETIME_T"sv;
    case CURLINFO_CONTENT_LENGTH_DOWNLOAD:
      return "CURLINFO_CONTENT_LENGTH_DOWNLOAD"sv;
    case CURLINFO_CONTENT_LENGTH_DOWNLOAD_T:
      return "CURLINFO_CONTENT_LENGTH_DOWNLOAD_T"sv;
    case CURLINFO_CONTENT_LENGTH_UPLOAD:
      return "CURLINFO_CONTENT_LENGTH_UPLOAD"sv;
    case CURLINFO_CONTENT_LENGTH_UPLOAD_T:
      return "CURLINFO_CONTENT_LENGTH_UPLOAD_T"sv;
    case CURLINFO_STARTTRANSFER_TIME:
      return "CURLINFO_STARTTRANSFER_TIME"sv;
    case CURLINFO_CONTENT_TYPE:
      return "CURLINFO_CONTENT_TYPE"sv;
    case CURLINFO_REDIRECT_TIME:
      return "CURLINFO_REDIRECT_TIME"sv;
    case CURLINFO_REDIRECT_COUNT:
      return "CURLINFO_REDIRECT_COUNT"sv;
    case CURLINFO_PRIVATE:
      return "CURLINFO_PRIVATE"sv;
    case CURLINFO_HTTP_CONNECTCODE:
      return "CURLINFO_HTTP_CONNECTCODE"sv;
    case CURLINFO_HTTPAUTH_AVAIL:
      return "CURLINFO_HTTPAUTH_AVAIL"sv;
    case CURLINFO_PROXYAUTH_AVAIL:
      return "CURLINFO_PROXYAUTH_AVAIL"sv;
    case CURLINFO_OS_ERRNO:
      return "CURLINFO_OS_ERRNO"sv;
    case CURLINFO_NUM_CONNECTS:
      return "CURLINFO_NUM_CONNECTS"sv;
    case CURLINFO_SSL_ENGINES:
      return "CURLINFO_SSL_ENGINES"sv;
    case CURLINFO_COOKIELIST:
      return "CURLINFO_COOKIELIST"sv;
    case CURLINFO_LASTSOCKET:
      return "CURLINFO_LASTSOCKET"sv;
    case CURLINFO_FTP_ENTRY_PATH:
      return "CURLINFO_FTP_ENTRY_PATH"sv;
    case CURLINFO_REDIRECT_URL:
      return "CURLINFO_REDIRECT_URL"sv;
    case CURLINFO_PRIMARY_IP:
      return "CURLINFO_PRIMARY_IP"sv;
    case CURLINFO_APPCONNECT_TIME:
      return "CURLINFO_APPCONNECT_TIME"sv;
    case CURLINFO_CERTINFO:
      return "CURLINFO_CERTINFO"sv;
    case CURLINFO_CONDITION_UNMET:
      return "CURLINFO_CONDITION_UNMET"sv;
    case CURLINFO_RTSP_SESSION_ID:
      return "CURLINFO_RTSP_SESSION_ID"sv;
    case CURLINFO_RTSP_CLIENT_CSEQ:
      return "CURLINFO_RTSP_CLIENT_CSEQ"sv;
    case CURLINFO_RTSP_SERVER_CSEQ:
      return "CURLINFO_RTSP_SERVER_CSEQ"sv;
    case CURLINFO_RTSP_CSEQ_RECV:
      return "CURLINFO_RTSP_CSEQ_RECV"sv;
    case CURLINFO_PRIMARY_PORT:
      return "CURLINFO_PRIMARY_PORT"sv;
    case CURLINFO_LOCAL_IP:
      return "CURLINFO_LOCAL_IP"sv;
    case CURLINFO_LOCAL_PORT:
      return "CURLINFO_LOCAL_PORT"sv;
    case CURLINFO_TLS_SESSION:
      return "CURLINFO_TLS_SESSION"sv;
    case CURLINFO_ACTIVESOCKET:
      return "CURLINFO_ACTIVESOCKET"sv;
    case CURLINFO_TLS_SSL_PTR:
      return "CURLINFO_TLS_SSL_PTR"sv;
    case CURLINFO_HTTP_VERSION:
      return "CURLINFO_HTTP_VERSION"sv;
    case CURLINFO_PROXY_SSL_VERIFYRESULT:
      return "CURLINFO_PROXY_SSL_VERIFYRESULT"sv;
    case CURLINFO_PROTOCOL:
      return "CURLINFO_PROTOCOL"sv;
    case CURLINFO_SCHEME:
      return "CURLINFO_SCHEME"sv;
    case CURLINFO_TOTAL_TIME_T:
      return "CURLINFO_TOTAL_TIME_T"sv;
    case CURLINFO_NAMELOOKUP_TIME_T:
      return "CURLINFO_NAMELOOKUP_TIME_T"sv;
    case CURLINFO_CONNECT_TIME_T:
      return "CURLINFO_CONNECT_TIME_T"sv;
    case CURLINFO_PRETRANSFER_TIME_T:
      return "CURLINFO_PRETRANSFER_TIME_T"sv;
    case CURLINFO_STARTTRANSFER_TIME_T:
      return "CURLINFO_STARTTRANSFER_TIME_T"sv;
    case CURLINFO_REDIRECT_TIME_T:
      return "CURLINFO_REDIRECT_TIME_T"sv;
    case CURLINFO_APPCONNECT_TIME_T:
      return "CURLINFO_APPCONNECT_TIME_T"sv;
    case CURLINFO_RETRY_AFTER:
      return "CURLINFO_RETRY_AFTER"sv;
    case CURLINFO_EFFECTIVE_METHOD:
      return "CURLINFO_EFFECTIVE_METHOD"sv;
    case CURLINFO_PROXY_ERROR:
      return "CURLINFO_PROXY_ERROR"sv;
    case CURLINFO_REFERER:
      return "CURLINFO_REFERER"sv;
    case CURLINFO_CAINFO:
      return "CURLINFO_CAINFO"sv;
    case CURLINFO_CAPATH:
      return "CURLINFO_CAPATH"sv;
    case CURLINFO_XFER_ID:
      return "CURLINFO_XFER_ID"sv;
    case CURLINFO_CONN_ID:
      return "CURLINFO_CONN_ID"sv;
    case CURLINFO_QUEUE_TIME_T:
      return "CURLINFO_QUEUE_TIME_T"sv;
    case CURLINFO_USED_PROXY:
      return "CURLINFO_USED_PROXY"sv;
    case CURLINFO_POSTTRANSFER_TIME_T:
      return "CURLINFO_POSTTRANSFER_TIME_T"sv;
    case CURLINFO_EARLYDATA_SENT_T:
      return "CURLINFO_EARLYDATA_SENT_T"sv;
    case CURLINFO_HTTPAUTH_USED:
      return "CURLINFO_HTTPAUTH_USED"sv;
    case CURLINFO_PROXYAUTH_USED:
      return "CURLINFO_PROXYAUTH_USED"sv;
    case CURLINFO_SIZE_DELIVERED:
      return "CURLINFO_SIZE_DELIVERED"sv;
    case CURLINFO_LASTONE:
      return "CURLINFO_LASTONE"sv;
    default:
      unknown = absl::StrCat("<unknown CURLINFO: ", std::to_underlying(info), ">");
      return unknown;
  }
}
#pragma clang diagnostic pop
