name: CI

on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: windows-latest
    env:
      _VCPKG_: ${{ github.workspace }}/third_party/vcpkg
      _LLVM_: C:\Program Files\LLVM\bin\
      VCPKG_EXE: ${{ github.workspace }}/third_party/vcpkg/vcpkg
      BUILD_DIR: ${{ github.workspace }}/build/ci
      FEED_URL: https://nuget.pkg.github.com/riftcr/index.json
      VCPKG_BINARY_SOURCES: 'clear;nuget,https://nuget.pkg.github.com/riftcr/index.json,readwrite'
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Convert vcpkg to full clone
        working-directory: ${{ env._VCPKG_ }}
        run: |
          git fetch --unshallow origin
      - name: Bootstrap vcpkg
        shell: pwsh
        run: ${{ env._VCPKG_ }}/bootstrap-vcpkg.bat
      - name: Add NuGet sources
        shell: pwsh
        run: |
          .$(${{ env.VCPKG_EXE }} fetch nuget) `
            sources add `
            -Source "${{ env.FEED_URL }}" `
            -StorePasswordInClearText `
            -Name GitHubPackages `
            -UserName "riftcr" `
            -Password "${{ secrets.VCPKG_PAT }}"
          .$(${{ env.VCPKG_EXE }} fetch nuget) `
            setapikey "${{ secrets.VCPKG_PAT}}" `
            -Source "${{ env.FEED_URL }}"
      - name: Install LLVM/Clang 22
        shell: pwsh
        run: |
            Invoke-WebRequest -Uri "https://github.com/llvm/llvm-project/releases/download/llvmorg-22.1.8/clang+llvm-22.1.8-x86_64-pc-windows-msvc.tar.xz" -OutFile "$env:RUNNER_TEMP\llvm.tar.xz"
            mkdir "C:\LLVM22" | Out-Null
            tar -xJf "$env:RUNNER_TEMP\llvm.tar.xz" -C "C:\LLVM22" --strip-components=1
            Add-Content $env:GITHUB_PATH "C:\LLVM22\bin"
            Add-Content $env:GITHUB_ENV "LLVM_DIR=C:\LLVM22"
            Add-Content $env:GITHUB_ENV "CMAKE_PREFIX_PATH=C:\LLVM22"
      - name: 'CMake: configure'
        run: cmake --preset ci
      - name: 'CMake: build'
        run: cmake --build --preset ci
      - name: Prepare artifacts
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force "${{ runner.temp }}\artifacts" | Out-Null
          New-Item -ItemType Directory -Force "${{ runner.temp }}\symbols" | Out-Null
          Copy-Item "${{ env.BUILD_DIR }}\launcher\riftcrack-launcher.exe" "${{ runner.temp }}\artifacts\riftcrack-launcher.exe"
          Copy-Item "${{ env.BUILD_DIR }}\launcher\riftcrack-launcher.pdb" "${{ runner.temp }}\symbols\riftcrack-launcher.pdb"
          Copy-Item "${{ env.BUILD_DIR }}\src\rc.dll" "${{ runner.temp }}\artifacts\rc.dll"
          Copy-Item "${{ env.BUILD_DIR }}\src\rc.pdb" "${{ runner.temp }}\symbols\rc.pdb"
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: riftcrack
          path: ${{ runner.temp }}/artifacts/*
      - name: Upload debug symbols
        uses: actions/upload-artifact@v5
        with:
          name: symbols
          path: ${{ runner.temp }}/symbols/*
